# config/routes.yml
cargus_generate_awb:
  path: /cargus/awb/generate/{orderId}
  methods: [GET, POST]
  defaults:
    _controller: 'Cargus\Controller\Admin\CargusAwbController::generateAwbAction'
    _legacy_controller: 'AdminOrders'

cargus_print_awb:
  path: /cargus/awb/print/{awbNumber}
  methods: [GET]
  defaults:
    _controller: 'Cargus\Controller\Admin\CargusPrintController::printAwbAction'
    _legacy_controller: 'AdminOrders'

cargus_return_awb:
  path: /cargus/awb/return/{orderId}
  methods: [POST]
  defaults:
    _controller: 'Cargus\Controller\Admin\CargusReturnController::generateReturnAction'
    _legacy_controller: 'AdminOrders'